### ISSUE TITLE
브랜치 머지 관련

### ISSUE THREAD

**Issue by jy222ce** [jy222ce/AngryData#4]
- 브랜치는 팠나요?
- 브랜치 사용법은 익혔나요?
- 코드리뷰를 할 생각이 있나요?

**Comment by mumbb** [comment]
아 하면 되잖아요 ㅜ

**Comment by mumbb** [comment]
했는데 왜 안 받아주세요....?!!!!

@jy222ce

**Comment by mumbb** [comment]
어머야 내가하는 거였네 저 했어요

**Comment by jy222ce** [comment]
보채지마세욧

2020년 9월 22일 (화) 오후 1:51, mumbb <notifications@github.com>님이 작성:

**Comment by mumbb** [comment]
아 이거 제가해도 되는 거엿어욧 히히

근데 왜 미션 컴플리트 안뜨나요 그런거 안뜨나요?
